### ISSUE TITLE
Compose DP

### ISSUE THREAD

**Issue by medkhabt** [FaridAsgarov/ArmyPattern#10]
Hi there! I love your project, i think i'll learn a lot just by watching your code. I noticed something and i wanted to know your opinion about it. 
the class BaseArmor.java Is the component that the composite extend from
https://github.com/FaridAsgarov/ArmyPattern/blob/a7f1a18017111a838698649cbdc43a3cdc02677e/src/com/company/armor_factory/BaseArmor.java#L3

Is it not better to make it an abstract class, so it can't be instantiated without an implementation. Or is there a case where you want to use ( new BaseArmor() ) Without specifying which baseArmor you want.

**Comment by FaridAsgarov** [comment]
Hi there! I am still learning, so I am sure I make some mistakes in the code :) Yes, you are right, it is better to make BaseArmor an abstract class. I do not expect to instantiate it without an implementation. I expect to always implement it through its subclasses, from concreteArmorElements package ---> one of the six materials ---> one of the four specific BodyPartArmor pieces. So yes, you are right, good Sir 👍

**Comment by medkhabt** [comment]
Good luck with your project, it seems fun!

**Comment by FaridAsgarov** [comment]
Thank you, good luck with your projects as well :)
